# Generated by Django 3.2.18 on 2023-08-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20, null=True)),
                ('Telephone', models.CharField(max_length=8)),
                ('Interventions', models.PositiveIntegerField(default=0)),
                ('Date_Created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20, null=True)),
                ('Telephone', models.CharField(max_length=8)),
                ('Modele_Couture', models.TextField(max_length=100, null=True)),
                ('Nombre_Pagnes', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Dos', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Epaule', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Poitrine', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Manche', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Tour_Manche', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Taille', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Tour_Taille', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Pince_longueur_seins', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Camisole', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Robe', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Chemise', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Messure_Bassin', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Mesure_Ceinture', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Mesure_Cuisse', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Mesure_Genoux', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longeur_Jupe', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Bras', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Longueur_Poignet', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Prix_Couture', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Avance', models.DecimalField(decimal_places=2, max_digits=100000, null=True)),
                ('Date_Depot_Model', models.DateTimeField(auto_now=True)),
                ('Date_Retrait_Model', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='Couturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=30, null=True, verbose_name='Nom')),
                ('Firstname', models.CharField(max_length=30, null=True, verbose_name='Prenom')),
                ('Company', models.CharField(max_length=30, null=True, verbose_name='Nom de votre entreprise')),
                ('Email', models.EmailField(max_length=254, null=True, verbose_name='Adresse mail')),
                ('Password', models.CharField(max_length=20, null=True, verbose_name='Mot de passe')),
                ('PasswordConfirm', models.CharField(max_length=20, null=True, verbose_name='Confirmer votre mot de passe')),
            ],
            options={
                'verbose_name': 'Couturier',
                'verbose_name_plural': 'Couturiers',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Nom', models.CharField(max_length=60)),
                ('Telephone', models.CharField(max_length=8, unique=True)),
                ('Modele_couture', models.CharField(max_length=100)),
                ('Prix_Couture', models.PositiveBigIntegerField()),
                ('Avance', models.PositiveBigIntegerField()),
                ('Solde', models.PositiveSmallIntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.commande')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
    ]
