# Generated by Django 3.2.18 on 2023-08-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Telephone',
            field=models.CharField(max_length=8),
        ),
    ]
