# Generated by Django 3.2.18 on 2023-09-01 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_facture_fichier_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date_Depot_Model',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
