# Generated by Django 3.2.18 on 2023-09-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_commande_date_retrait_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date_Depot_Model',
            field=models.DateTimeField(default='2323-12-04'),
        ),
    ]
