# Generated by Django 3.2.18 on 2023-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230906_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date_Retrait_Model',
            field=models.DateTimeField(),
        ),
    ]
