# Generated by Django 3.2.18 on 2023-09-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_commande_date_retrait_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Avance',
            field=models.DecimalField(decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Prix_Couture',
            field=models.DecimalField(decimal_places=2, max_digits=100000, null=True),
        ),
    ]
