# Generated by Django 3.2.18 on 2023-09-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230908_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Avance',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='Prix_Couture',
            field=models.PositiveBigIntegerField(),
        ),
    ]
