# Generated by Django 3.2.18 on 2023-09-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230908_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Avance',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='Prix_Couture',
            field=models.PositiveBigIntegerField(),
        ),
    ]
