# Generated by Django 3.2.18 on 2023-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230908_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Solde',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
