# Generated by Django 3.2.18 on 2023-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230912_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='Date_Retrait_Model',
            field=models.DateField(),
        ),
    ]
